### ISSUE TITLE
Google Bewertungen

### ISSUE THREAD

**Issue by LucasByteforest** [LucasByteforest/RentABike#1]
bitte noch die Google Bewertungen einbringen. 
Du kannst hier gerne einen Vorschlag machen

**Comment by south-bird** [comment]
Hier würde ich dies über ein Plugin lösen. Vor kurzer Zeit habe ich dies benutzt welches super funktioniert hat.

https://wordpress.org/plugins/g-business-reviews-rating/
Hier müsste dann aber eine Google Developer Konto angelegt sein, welches die entspreche API zur Verfügung stellt.

Ich kann mir auch das folgende Plugin vorstellen, welches auch einen Sliders ermöglicht

https://wordpress.org/plugins/wp-reviews-plugin-for-google/#%0Awhat%20can%20i%20set%20in%20the%20free%20mode%3F%0A

Eins von beiden kann ich gerne einbauen, benötige dann aber die entsprechende API

**Comment by LucasByteforest** [comment]
Wir haben uns dafür entschieden das ohne Plugin zu lösen. Also wir würden einen Banner per img einfügen und Kundenbewertungen dann einfach als Zitate. Ähnlich wie hier: http://baatzberlin.v121787.goserver.host 
Dort ist das img vom Banner im Head Bereich und weiter unten die Zitate und Bewertungen

**Comment by south-bird** [comment]
Siegel & Bewertungen habe ich hinzugefügt

**Comment by LucasByteforest** [comment]
Verschiebe es gerne zwischen die beiden Bereiche, sodass es relativ weit oben ist.

<img width="1612" alt="siegel" src="https://user-images.githubusercontent.com/25614305/92968714-eba78300-f47b-11ea-97c7-b09874f906d0.png">

**Comment by south-bird** [comment]
Habe die Bereiche verschoben
