### ISSUE TITLE
Reservierungsformular Farradverleih

### ISSUE THREAD

**Issue by LucasByteforest** [LucasByteforest/RentABike#10]
Orientiere dich bitte hier mehr an der alten Seite: http://rentabike-berlin.de/anfrage_fahrradverleih.aspx  

Wir brauchen eine Auswahl für:
- E-Bikes, Tandems, Bikes -> nach der Auswahl für das Fahrrad eine Auswahl für Herren/Damen/ Kinderräder (außer bei Tandems) 
- Datum von bis 

- Kontaktdaten

**Comment by south-bird** [comment]
Formular habe ich überarbeitet

**Comment by LucasByteforest** [comment]
Formular ist super. 
noch zwei Dinge: 
1. Die dunklen Schriften sind nicht lesbar 
2. Bitte dieses Formular nur bei Fahrradverleih und bei jetzt Anfragen bzw. Fahrrad reservieren verwenden (aktuell noch bei Souvenir Shop drin)

**Comment by LucasByteforest** [comment]
und "E-Bike" auch Komplett unter das Kästchen. Das E steht gerade daneben

**Comment by south-bird** [comment]
Angepasst
