### ISSUE TITLE
Preistabelle aktualisieren

### ISSUE THREAD

**Issue by LucasByteforest** [LucasByteforest/RentABike#12]
Der Kunde hat mir neue Infos zu Preisen gegeben. 

Fahrrad:
2h 6€
4h 8€
24h 12€

Tandem: 
2h 16€
4h 19€
24h 29€ 

E-Bike: 
2h 16€
4h 19€
8h 29€
24h 39€ + 300€ Kaution

**Comment by south-bird** [comment]
Preise aktualisiert

**Comment by LucasByteforest** [comment]
kannst du den Text über die ganze Breite des Kastens strecken und etwas größer machen ?

**Comment by south-bird** [comment]
Ich habe die Preistabelle nochmal überarbeitet. Ich denke so ist es noch etwas übersichtlicher

**Comment by south-bird** [comment]
Ich habe die Preistabelle nochmal überarbeitet. Ich denke so ist es noch etwas übersichtlicher
