### ISSUE TITLE
Informationen zu Fahrrädern

### ISSUE THREAD

**Issue by LucasByteforest** [LucasByteforest/RentABike#14]
diese Informationen müssen in die jeweiligen Sektionen auf der Unterseite Fahrradverleih:

Bikes: 

Laufräder: 
16 Zoll, 20 Zoll, 24 Zoll, 26 Zoll, 28 Zoll 
- Laufräder für jedes Alter und für jede Größe vorhanden 

Tandem: 

Cruiser -> 3 Gänge
Tourer -> 21 Gängen
Laufräder 26 Zoll 

E-Bike: 

- Hochwertige Bosch Motoren
- Akku mit 400 Watt
- Reichweite bis zu 90km 
- Laufräder 28 Zoll 
- auch große Rahmen erhältlich 

Pack gerne Bespieltet dazwischen, dass der Kunde diese Tete formulieren kann.

**Comment by south-bird** [comment]
Infos hinzugefügt

**Comment by LucasByteforest** [comment]
kannst du die Infos bei E-Bikes etwas ansehnlicher darstellen ? Vielleicht mit icons versehen oder etwas anordnen

**Comment by south-bird** [comment]
Hab es mit Icons umgesetzt
