### ISSUE TITLE
User Test - Kleinigkeiten

### ISSUE THREAD

**Issue by LucasByteforest** [LucasByteforest/RentABike#18]
ich habe gerade mal einen User Test von einem potentiellen Touristen machen lassen. 
folgende Dinge sind noch aufgefallen:

1. Auf der Startseite die Boxen sind super. Mache bitte dennoch nicht klickbar, da dies zu verwirrend ist und man einige Informationen nicht bekommt (wie z.B.) die Preise. Schreibe unter die Boxen einen Button "zum Fahrradverleih" wo man auf die zweite Unterseite kommt. Die Boxen auf der Unterseite "Fahrradverleih" bleiben klickbar. 

2. zur schnelleren Abwicklung mache bei den Sektionen für Fahrräder, Tandems und E-Bikes noch einen Button ("jetzt Fahrrad buchen" "jetzt Tandem buchen" und "jetzt E-Bike buchen"). Richtig gut wäre, wenn im Formular dann noch die richtige Box vorausgewählt ist. Wenn es zu kompliziert ist ist das aber auch kein Problem.  

Sonst ist die Seite super beim User angekommen und sehr einfach zu handeln. Gute Arbeit.

**Comment by south-bird** [comment]
Danke dir für dein Feedback. 1 & 2 habe ich umgesetzt. Nr. 2 mit dem automatischen hinzufügen der Boxen gerne einmal testen.
