### ISSUE TITLE
Blickfang

### ISSUE THREAD

**Issue by LucasByteforest** [LucasByteforest/RentABike#2]
Der Kunde möchte einen Blickfang auf der Seite haben: 

STOP nicht mehr alte Adresse sondern neue Adresse -> Kochstraße 1. 

irgendwie etwas auffälliges einbauen

**Comment by south-bird** [comment]
Schau mal ob das "Stop" Zeichen auffällig genug ist.

Ebenfalls hatte ich auch noch die Idee ein freigestelltes Foto einzubauen.

**Comment by LucasByteforest** [comment]
Ist zu weit nach links gerutscht und abgeschnitten

**Comment by south-bird** [comment]
habe es für etwas kleinere Bildschirme angepasst.
