### ISSUE TITLE
Anhalter Bahnhof als zweiten Standort erwähnen (im Text)

### ISSUE THREAD

**Issue by LucasByteforest** [LucasByteforest/RentABike#20]
Bei allen Erwähnungen Checkpoint Charlie auch Anhalter Bahnhof erwähnen (als zweiten Standort) -> siehe Kontakt, dort habe ich es kurz geändert

Text auf Startseite: Abholung Checkpoint/Anhalter Bahnhof immer erwähnen

**Comment by south-bird** [comment]
Anhalter Bahnhof hinzugefügt
