### ISSUE TITLE
Reservierungsformular

### ISSUE THREAD

**Issue by LucasByteforest** [LucasByteforest/RentABike#21]
Bei Reservierung : Name/ Vorname

Adresse als neuer Ausfüllblock

E-Mail: nur Kleinschreibung erlaubt 

Alle Felder müssen ausgefüllt sein und ein * sichtbar sonst nicht absendbar (außer Anmerkung ist optional) 

Helme Reservieren (tick Box + Anzahl -> wenn getickt wird erscheint Anzahl) neues Feld unter Anzahl der Fahrräder  

irgendwo klein dazu: Fahrrad Körbe und ABUS Schlösser im Preis inbegriffen

**Comment by south-bird** [comment]
- Text Namesfeld angepasst
- Adresse hinzugefügt
- Pflichtfelder hinzugefügt
- Helme reservieren hinzugefügt
- kurzen Text hinzugefügt
