### ISSUE TITLE
Auswahl zwischen City Bikes und Beach Cruiser

### ISSUE THREAD

**Issue by LucasByteforest** [LucasByteforest/RentABike#23]
In der Sektion City-Bikes _(Fahrradverleih -> City Bikes) muss einmal die City Bikes und einmal die Beach Cruisewr beschrieben werden (das recht Bild davon). 

Außerdem auch eine Auswahl zwischen City Bike und Beach Cruisern im Formular anlegen.

**Comment by south-bird** [comment]
Fahrrad in City Bike geändert + Beach Cruiser hinzugefügt
