### ISSUE TITLE
mobil -> Fahrrad reservieren

### ISSUE THREAD

**Issue by LucasByteforest** [LucasByteforest/RentABike#24]
So es kann nun weiter gehen. Wir machen die deutsche Website jetzt fertig, sodass eventuell "nur" noch die Englische Übersetzung dazukommt. 

Der Kunde möchte, dass man mobil unter Fahrrad reservieren nach dem Header das Formular sieht und nicht den Text. Vielleicht dann mobil den Text unter das Formular verfrachten oder sonst mobil einfach weg.

**Comment by south-bird** [comment]
Hab ich einmal angepasst. Schau mal ob es so in Ordnung ist.
