### ISSUE TITLE
Souvenir Shop -> Service

### ISSUE THREAD

**Issue by LucasByteforest** [LucasByteforest/RentABike#26]
Wir sollen nun die Souvenir Shop Unterseite löschen und daraus eine Service Seite machen

Inhalte: 
Platten Reperatur 
Full Check (Inspektion)
Reifen-Bremsen-Kette 

Gerne erstmal mit Lore Ipsum Texten, wir entwerfen dann die Texte

**Comment by south-bird** [comment]
Ich habe die Seite soweit einmal vorbereitet.
