### ISSUE TITLE
footer Telefon

### ISSUE THREAD

**Issue by LucasByteforest** [LucasByteforest/RentABike#3]
Im Footer ist die Nummer schwarz und nicht gut lesbar

**Comment by LucasByteforest** [comment]
ist immer noch schwarz

**Comment by south-bird** [comment]
Dies ist aber hartnäckig, nur bei mir scheint alles okay. Kannst du nochmal die Seite aktualisieren.
Falls es immer noch schwarz ist. Welchen Browser nutzt du?
