### ISSUE TITLE
Umleitung

### ISSUE THREAD

**Issue by LucasByteforest** [LucasByteforest/RentABike#31]
Wir haben die Website nun auf http://rentabike-berlin.de/ umgeleitet. 

Kannst du dich bitte um die nötigen WordPress Einstellungen kümmern ?

**Comment by south-bird** [comment]
Kann ich machen. Leider kann ich mich aber noch nicht ins Backend einloggen. Dies sollte mit einem Datenbank-Eintrag erledigt sein. Kannst du wp_options in der Datenbank anpassen über phpmyadmin?

**Comment by LucasByteforest** [comment]
https://www.rentabike.paula.hostkraft.de/wp-admin/ 

du kannst dich doch noch hier einloggen und unter den allgemeinen Einstellungen die Website Informationen ändern oder liege ich da falsch ?

**Comment by south-bird** [comment]
Ja, stimmt hab ich jetzt so nicht dran gedacht. Eine Live-Schaltung geh ich sonst anders an, aber ich denke ich sollte es nun hinkriegen.

**Comment by south-bird** [comment]
Was du dir noch anschauen müsstest. wäre das SSL Zertifikat. Da stimmt etwas noch nicht.

**Comment by LucasByteforest** [comment]
SSL habe ich umgestellt. Nun müsste alles passen. 
Check gerne noch einmal abschließend ob alles funktioniert (Formulare, Links, mobil etc).

**Comment by south-bird** [comment]
Sieht soweit alles gut aus, außer beim SSL scheint es noch Probleme zu geben.
Ich würde dem Kunden auch nochmal empfehlen die Formulare zu testen, ob alle bei Ihm ankommen.
