### ISSUE TITLE
WhatsApp Reservierung

### ISSUE THREAD

**Issue by LucasByteforest** [LucasByteforest/RentABike#4]
Bitte im Bereich "jetzt online Reservieren" auch die Option mit WhatsApp hinzufügen. 
So etwas wie: "Ganz bequem auch über WhatsApp Fahrräder reservieren oder Fragen stellen" (noch nicht ausformuliert) + WhatsApp Button. 

<img width="1413" alt="WhatsApp" src="https://user-images.githubusercontent.com/25614305/91966874-bcbe3e00-ed12-11ea-8b85-2c27684b87f2.png">

**Comment by south-bird** [comment]
Habe es WhatsApp hinzugefügt

**Comment by LucasByteforest** [comment]
Hover des Buttons passt nicht und Button bitte auch in diesem orange. Das passt sonst nicht zur Website. 
<img width="950" alt="whatsA0p" src="https://user-images.githubusercontent.com/25614305/92106675-08411c80-ede5-11ea-8a6e-169f5511fb07.png">
