### ISSUE TITLE
Sektion Preistabelle

### ISSUE THREAD

**Issue by LucasByteforest** [LucasByteforest/RentABike#5]
Preistabelle verschoben (auch auf der Seite "Fahrradverleih")

Link rechts passt nicht. Gerne den Link farblich etwas abheben 

![Issue1](https://user-images.githubusercontent.com/25614305/94667935-b7ebaa80-030f-11eb-8ec2-a886e3bc931b.png)

**Comment by south-bird** [comment]
War noch ein Problem bei Safari.
Link habe ich hervorgehoben.
