### ISSUE TITLE
Fahrradverleih

### ISSUE THREAD

**Issue by LucasByteforest** [LucasByteforest/RentABike#6]
Füge gerne eine Sektion für E-Bikes, eine für Tandems und eine für "normale" Bikes hinzu. Bei einem Click auf die Box scrollt man zur jeweiligen Sektion. 

Ich Frage auch Bilder zur jeweiligen Fahrradart an. Gerne erst einmal ein Beispielbild nehmen

**Comment by south-bird** [comment]
Habe die 3 Sektionen hinzugefügt
