### ISSUE TITLE
Adresse

### ISSUE THREAD

**Issue by LucasByteforest** [LucasByteforest/RentABike#7]
Die Adresse bitte zu Kochstraße 1 ändern
![IssueAdresse](https://user-images.githubusercontent.com/25614305/94671183-d5227800-0313-11eb-9961-953baaceb1ca.png)

**Comment by south-bird** [comment]
Adresse hab ich geändert.

**Comment by LucasByteforest** [comment]
schreibe auf der Kontaktseite für die mobile Besucher auch gerne dazu: 
 "Gerne können Sie uns auch per WhatsApp kontaktieren!" und ein Icon dazu
